-- ============================================================
-- PROYECTO ACCESOS V2 - ETAPA 1
-- Catalogos, nodos, administradores, accesos, personal y SCTR.
--
-- Diseñado para ejecutarse en un proyecto Supabase NUEVO Y VACIO.
-- No elimina tablas ni datos existentes.
-- ============================================================

BEGIN;

-- ============================================================
-- 1. CATALOGOS
-- ============================================================

CREATE TABLE IF NOT EXISTS public.tipos_documento (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS public.niveles_acceso (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS public.tipos_trabajo (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  gestiona_equipos BOOLEAN NOT NULL DEFAULT FALSE,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS public.empresas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS public.areas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id INTEGER NOT NULL
    REFERENCES public.empresas(id) ON DELETE RESTRICT,
  nombre TEXT NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT areas_empresa_nombre_unique UNIQUE (empresa_id, nombre)
);

CREATE TABLE IF NOT EXISTS public.nodos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  requiere_llave BOOLEAN NOT NULL DEFAULT FALSE,
  netbox_site_id INTEGER UNIQUE,
  activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- ============================================================
-- 2. ADMINISTRADORES
-- Solo los usuarios registrados aqui tienen permisos de admin.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.administradores (
  user_id UUID PRIMARY KEY
    REFERENCES auth.users(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION public.es_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.administradores a
    WHERE a.user_id = auth.uid()
      AND a.activo = TRUE
  );
$$;

REVOKE ALL ON FUNCTION public.es_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.es_admin() TO authenticated;

-- ============================================================
-- 3. SOLICITUDES DE ACCESO
-- El id numerico es interno. codigo_seguimiento es el codigo
-- que se entregara al tecnico para consultar su solicitud.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.accesos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_seguimiento UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,

  nodo_id INTEGER NOT NULL
    REFERENCES public.nodos(id) ON DELETE RESTRICT,
  fecha_ingreso DATE NOT NULL,
  fecha_salida DATE NOT NULL,
  hora_ingreso TIME NOT NULL,
  hora_salida TIME NOT NULL,

  solicitante_nombre TEXT NOT NULL,
  solicitante_ap_paterno TEXT NOT NULL,
  solicitante_ap_materno TEXT NOT NULL,
  solicitante_tipo_doc_id INTEGER NOT NULL
    REFERENCES public.tipos_documento(id) ON DELETE RESTRICT,
  solicitante_num_doc TEXT NOT NULL,
  solicitante_telefono TEXT NOT NULL,
  solicitante_correo TEXT NOT NULL,

  nivel_acceso_id INTEGER NOT NULL
    REFERENCES public.niveles_acceso(id) ON DELETE RESTRICT,
  empresa_id INTEGER NOT NULL
    REFERENCES public.empresas(id) ON DELETE RESTRICT,
  area_responsable_id INTEGER NOT NULL
    REFERENCES public.areas(id) ON DELETE RESTRICT,
  area_apoyo_id INTEGER
    REFERENCES public.areas(id) ON DELETE RESTRICT,
  tipo_trabajo_id INTEGER NOT NULL
    REFERENCES public.tipos_trabajo(id) ON DELETE RESTRICT,
  detalle_trabajo TEXT,

  trabajo_contrata BOOLEAN NOT NULL DEFAULT FALSE,
  nombre_contrata TEXT,
  numero_personal INTEGER NOT NULL,

  estado_aprobacion TEXT NOT NULL DEFAULT 'PENDIENTE',
  estado_acceso TEXT NOT NULL DEFAULT 'PENDIENTE',
  motivo_cancelacion TEXT,
  hora_ingreso_real TIME,
  hora_salida_real TIME,

  aprobado_por UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  fecha_aprobacion TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT accesos_numero_personal_check
    CHECK (numero_personal BETWEEN 1 AND 8),
  CONSTRAINT accesos_fechas_check
    CHECK (fecha_salida >= fecha_ingreso),
  CONSTRAINT accesos_horario_check
    CHECK (
      fecha_salida > fecha_ingreso
      OR hora_salida > hora_ingreso
    ),
  CONSTRAINT accesos_contrata_check
    CHECK (
      (trabajo_contrata = FALSE AND nombre_contrata IS NULL)
      OR
      (trabajo_contrata = TRUE AND NULLIF(BTRIM(nombre_contrata), '') IS NOT NULL)
    ),
  CONSTRAINT accesos_estado_aprobacion_check
    CHECK (estado_aprobacion IN ('PENDIENTE', 'APROBADO', 'DENEGADO', 'CANCELADO')),
  CONSTRAINT accesos_estado_acceso_check
    CHECK (estado_acceso IN ('PENDIENTE', 'EN_NODO', 'ATENDIDO', 'CANCELADO')),
  CONSTRAINT accesos_aprobacion_consistente_check
    CHECK (
      (estado_aprobacion = 'PENDIENTE' AND aprobado_por IS NULL AND fecha_aprobacion IS NULL)
      OR
      (estado_aprobacion IN ('APROBADO', 'DENEGADO') AND aprobado_por IS NOT NULL AND fecha_aprobacion IS NOT NULL)
      OR
      (estado_aprobacion = 'CANCELADO')
    )
);

CREATE INDEX IF NOT EXISTS accesos_nodo_idx
  ON public.accesos(nodo_id);
CREATE INDEX IF NOT EXISTS accesos_fecha_ingreso_idx
  ON public.accesos(fecha_ingreso);
CREATE INDEX IF NOT EXISTS accesos_estado_aprobacion_idx
  ON public.accesos(estado_aprobacion);
CREATE INDEX IF NOT EXISTS accesos_tipo_trabajo_idx
  ON public.accesos(tipo_trabajo_id);

-- ============================================================
-- 4. PERSONAL Y DOCUMENTOS
-- Los documentos SCTR se guardaran en un bucket privado. Esta
-- tabla conserva solo la referencia y metadatos del archivo.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.personal_acceso (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  acceso_id BIGINT NOT NULL
    REFERENCES public.accesos(id) ON DELETE CASCADE,
  orden INTEGER NOT NULL,
  nombre TEXT NOT NULL,
  ap_paterno TEXT NOT NULL,
  ap_materno TEXT NOT NULL,
  tipo_doc_id INTEGER NOT NULL
    REFERENCES public.tipos_documento(id) ON DELETE RESTRICT,
  num_doc TEXT NOT NULL,
  telefono TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT personal_acceso_orden_check CHECK (orden BETWEEN 1 AND 8),
  CONSTRAINT personal_acceso_orden_unique UNIQUE (acceso_id, orden),
  CONSTRAINT personal_acceso_documento_unique UNIQUE (acceso_id, num_doc)
);

CREATE INDEX IF NOT EXISTS personal_acceso_acceso_idx
  ON public.personal_acceso(acceso_id);

CREATE TABLE IF NOT EXISTS public.acceso_documentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  acceso_id BIGINT NOT NULL
    REFERENCES public.accesos(id) ON DELETE CASCADE,
  storage_path TEXT NOT NULL UNIQUE,
  nombre_original TEXT NOT NULL,
  mime_type TEXT NOT NULL DEFAULT 'application/pdf',
  size_bytes BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT acceso_documentos_mime_check
    CHECK (mime_type = 'application/pdf'),
  CONSTRAINT acceso_documentos_size_check
    CHECK (size_bytes > 0 AND size_bytes <= 10485760)
);

CREATE INDEX IF NOT EXISTS acceso_documentos_acceso_idx
  ON public.acceso_documentos(acceso_id);

-- ============================================================
-- 5. UPDATED_AT
-- ============================================================

CREATE OR REPLACE FUNCTION public.actualizar_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS accesos_actualizar_updated_at ON public.accesos;
CREATE TRIGGER accesos_actualizar_updated_at
BEFORE UPDATE ON public.accesos
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_updated_at();

-- ============================================================
-- 6. ROW LEVEL SECURITY
-- En esta etapa los visitantes solo pueden leer catalogos.
-- La creacion publica de solicitudes se agregara mediante una
-- funcion transaccional controlada en una migracion posterior.
-- ============================================================

ALTER TABLE public.tipos_documento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.niveles_acceso ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tipos_trabajo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.empresas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nodos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.administradores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accesos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.personal_acceso ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.acceso_documentos ENABLE ROW LEVEL SECURITY;

CREATE POLICY tipos_documento_lectura_publica
ON public.tipos_documento FOR SELECT
TO anon, authenticated
USING (activo = TRUE);

CREATE POLICY niveles_acceso_lectura_publica
ON public.niveles_acceso FOR SELECT
TO anon, authenticated
USING (activo = TRUE);

CREATE POLICY tipos_trabajo_lectura_publica
ON public.tipos_trabajo FOR SELECT
TO anon, authenticated
USING (activo = TRUE);

CREATE POLICY empresas_lectura_publica
ON public.empresas FOR SELECT
TO anon, authenticated
USING (activo = TRUE);

CREATE POLICY areas_lectura_publica
ON public.areas FOR SELECT
TO anon, authenticated
USING (activo = TRUE);

CREATE POLICY nodos_lectura_publica
ON public.nodos FOR SELECT
TO anon, authenticated
USING (activo = TRUE);

CREATE POLICY catalogos_gestion_admin_tipos_documento
ON public.tipos_documento FOR ALL TO authenticated
USING (public.es_admin()) WITH CHECK (public.es_admin());
CREATE POLICY catalogos_gestion_admin_niveles_acceso
ON public.niveles_acceso FOR ALL TO authenticated
USING (public.es_admin()) WITH CHECK (public.es_admin());
CREATE POLICY catalogos_gestion_admin_tipos_trabajo
ON public.tipos_trabajo FOR ALL TO authenticated
USING (public.es_admin()) WITH CHECK (public.es_admin());
CREATE POLICY catalogos_gestion_admin_empresas
ON public.empresas FOR ALL TO authenticated
USING (public.es_admin()) WITH CHECK (public.es_admin());
CREATE POLICY catalogos_gestion_admin_areas
ON public.areas FOR ALL TO authenticated
USING (public.es_admin()) WITH CHECK (public.es_admin());
CREATE POLICY catalogos_gestion_admin_nodos
ON public.nodos FOR ALL TO authenticated
USING (public.es_admin()) WITH CHECK (public.es_admin());

CREATE POLICY administradores_lectura_propia
ON public.administradores FOR SELECT TO authenticated
USING (user_id = auth.uid() OR public.es_admin());

CREATE POLICY administradores_gestion_admin
ON public.administradores FOR ALL TO authenticated
USING (public.es_admin()) WITH CHECK (public.es_admin());

CREATE POLICY accesos_gestion_admin
ON public.accesos FOR ALL TO authenticated
USING (public.es_admin()) WITH CHECK (public.es_admin());

CREATE POLICY personal_acceso_gestion_admin
ON public.personal_acceso FOR ALL TO authenticated
USING (public.es_admin()) WITH CHECK (public.es_admin());

CREATE POLICY acceso_documentos_gestion_admin
ON public.acceso_documentos FOR ALL TO authenticated
USING (public.es_admin()) WITH CHECK (public.es_admin());

-- Privilegios de API. RLS sigue determinando que filas son visibles.
GRANT SELECT ON
  public.tipos_documento,
  public.niveles_acceso,
  public.tipos_trabajo,
  public.empresas,
  public.areas,
  public.nodos
TO anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON
  public.tipos_documento,
  public.niveles_acceso,
  public.tipos_trabajo,
  public.empresas,
  public.areas,
  public.nodos,
  public.administradores,
  public.accesos,
  public.personal_acceso,
  public.acceso_documentos
TO authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- ============================================================
-- 7. DATOS INICIALES
-- ============================================================

INSERT INTO public.tipos_documento (nombre)
VALUES ('DNI'), ('CE')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO public.niveles_acceso (nombre)
VALUES ('PROGRAMADO'), ('NO PROGRAMADO')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO public.tipos_trabajo (nombre, gestiona_equipos)
VALUES
  ('INSTALACION DE EQUIPOS', TRUE),
  ('RETIRO DE EQUIPOS', TRUE),
  ('REEMPLAZO DE EQUIPOS', TRUE),
  ('INGRESO_FO', TRUE),
  ('MANTENIMIENTO', FALSE)
ON CONFLICT (nombre) DO UPDATE
SET gestiona_equipos = EXCLUDED.gestiona_equipos;

INSERT INTO public.empresas (nombre)
VALUES ('WIN NET'), ('WIN EMPRESAS')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO public.areas (empresa_id, nombre)
SELECT e.id, v.nombre
FROM public.empresas e
JOIN (
  VALUES
    ('WIN NET', 'NOC-WIN'),
    ('WIN NET', 'INGENIERIA-WIN'),
    ('WIN EMPRESAS', 'NOC-EMPRESAS'),
    ('WIN EMPRESAS', 'IMPLEMENTACIONES-EMPRESAS')
) AS v(empresa, nombre)
  ON v.empresa = e.nombre
ON CONFLICT (empresa_id, nombre) DO NOTHING;

INSERT INTO public.nodos (nombre, requiere_llave, netbox_site_id)
VALUES
  ('200_MILLAS', TRUE, 146),
  ('3_DE_MAYO', TRUE, 125)
ON CONFLICT (nombre) DO UPDATE
SET
  requiere_llave = EXCLUDED.requiere_llave,
  netbox_site_id = EXCLUDED.netbox_site_id;

COMMIT;

-- ============================================================
-- VERIFICACION MANUAL DESPUES DE EJECUTAR
-- ============================================================
-- SELECT table_name
-- FROM information_schema.tables
-- WHERE table_schema = 'public'
-- ORDER BY table_name;
--
-- SELECT * FROM public.tipos_trabajo ORDER BY id;
-- SELECT * FROM public.nodos ORDER BY id;
