-- ============================================================
-- PROYECTO ACCESOS V2 - ETAPA 2
-- Solicitudes de instalacion, retiro, reemplazo e ingreso de FO.
--
-- Requiere haber ejecutado primero database/01_base_v2.sql.
-- No elimina tablas ni datos.
-- No ejecuta cambios en NetBox.
-- ============================================================

BEGIN;

-- ============================================================
-- 1. CABECERA DE LA SOLICITUD DE EQUIPOS
-- Una solicitud de acceso puede registrar como maximo un
-- formulario de gestion de equipos.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.movimientos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  acceso_id BIGINT NOT NULL UNIQUE
    REFERENCES public.accesos(id) ON DELETE CASCADE,
  tipo_movimiento TEXT NOT NULL,
  cantidad_items INTEGER NOT NULL,
  estado TEXT NOT NULL DEFAULT 'PENDIENTE',

  observacion_admin TEXT,
  error_general TEXT,
  aprobado_por UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  fecha_aprobacion TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT movimientos_tipo_check
    CHECK (tipo_movimiento IN (
      'INSTALACION',
      'RETIRO',
      'REEMPLAZO',
      'INGRESO_FO'
    )),
  CONSTRAINT movimientos_cantidad_check
    CHECK (cantidad_items BETWEEN 1 AND 50),
  CONSTRAINT movimientos_estado_check
    CHECK (estado IN (
      'PENDIENTE',
      'EN_REVISION',
      'PROCESANDO',
      'APROBADO',
      'DENEGADO',
      'ERROR'
    )),
  CONSTRAINT movimientos_decision_consistente_check
    CHECK (
      (estado IN ('PENDIENTE', 'EN_REVISION', 'PROCESANDO', 'ERROR'))
      OR
      (estado IN ('APROBADO', 'DENEGADO')
        AND aprobado_por IS NOT NULL
        AND fecha_aprobacion IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS movimientos_estado_idx
  ON public.movimientos(estado);
CREATE INDEX IF NOT EXISTS movimientos_tipo_idx
  ON public.movimientos(tipo_movimiento);
CREATE INDEX IF NOT EXISTS movimientos_created_at_idx
  ON public.movimientos(created_at DESC);

-- ============================================================
-- 2. DETALLE POR EQUIPO
--
-- RETIRO: una fila con accion RETIRO.
-- INSTALACION: una fila con accion INSTALACION.
-- REEMPLAZO: dos filas con el mismo numero_item y
-- grupo_reemplazo; una RETIRO y otra INSTALACION.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.movimiento_detalle (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  movimiento_id BIGINT NOT NULL
    REFERENCES public.movimientos(id) ON DELETE CASCADE,
  numero_item INTEGER NOT NULL,
  grupo_reemplazo INTEGER,
  accion TEXT NOT NULL,
  es_rackeable BOOLEAN NOT NULL,

  -- Fotografia del equipo existente cuando se solicita retiro.
  equipo_anterior_netbox_id INTEGER,
  equipo_anterior_nombre TEXT,
  equipo_anterior_fabricante TEXT,
  equipo_anterior_modelo TEXT,
  equipo_anterior_serial TEXT,
  equipo_anterior_rack_netbox_id INTEGER,
  equipo_anterior_rack_nombre TEXT,
  equipo_anterior_ru_inicio INTEGER,
  equipo_anterior_cantidad_ru INTEGER,

  -- Equipo nuevo solicitado para instalacion o reemplazo.
  manufacturer_netbox_id INTEGER,
  device_type_netbox_id INTEGER,
  fabricante TEXT,
  modelo TEXT,
  serial TEXT,
  nombre_propuesto TEXT,

  -- Datos que confirma o completa el administrador.
  nombre_aprobado TEXT,
  rack_aprobado_netbox_id INTEGER,
  rack_aprobado_nombre TEXT,
  ru_inicio_aprobada INTEGER,
  cantidad_ru INTEGER NOT NULL DEFAULT 1,

  -- Resultado devuelto por NetBox.
  equipo_resultado_netbox_id INTEGER,
  estado_ejecucion TEXT NOT NULL DEFAULT 'PENDIENTE',
  respuesta_netbox JSONB,
  error_netbox TEXT,
  ejecutado_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT movimiento_detalle_item_check
    CHECK (numero_item >= 1),
  CONSTRAINT movimiento_detalle_grupo_check
    CHECK (grupo_reemplazo IS NULL OR grupo_reemplazo >= 1),
  CONSTRAINT movimiento_detalle_accion_check
    CHECK (accion IN ('RETIRO', 'INSTALACION')),
  CONSTRAINT movimiento_detalle_cantidad_ru_check
    CHECK (cantidad_ru BETWEEN 1 AND 100),
  CONSTRAINT movimiento_detalle_estado_check
    CHECK (estado_ejecucion IN (
      'PENDIENTE',
      'EJECUTANDO',
      'EJECUTADO',
      'ERROR'
    )),
  CONSTRAINT movimiento_detalle_item_accion_unique
    UNIQUE (movimiento_id, numero_item, accion),
  CONSTRAINT movimiento_detalle_retiro_check
    CHECK (
      accion <> 'RETIRO'
      OR (
        equipo_anterior_netbox_id IS NOT NULL
        AND NULLIF(BTRIM(equipo_anterior_nombre), '') IS NOT NULL
      )
    ),
  CONSTRAINT movimiento_detalle_instalacion_check
    CHECK (
      accion <> 'INSTALACION'
      OR (
        manufacturer_netbox_id IS NOT NULL
        AND device_type_netbox_id IS NOT NULL
        AND NULLIF(BTRIM(nombre_propuesto), '') IS NOT NULL
      )
    ),
  CONSTRAINT movimiento_detalle_no_rack_check
    CHECK (
      es_rackeable = TRUE
      OR (
        rack_aprobado_netbox_id IS NULL
        AND rack_aprobado_nombre IS NULL
        AND ru_inicio_aprobada IS NULL
      )
    ),
  CONSTRAINT movimiento_detalle_ejecucion_consistente_check
    CHECK (
      (estado_ejecucion = 'PENDIENTE'
        AND ejecutado_at IS NULL
        AND error_netbox IS NULL)
      OR
      (estado_ejecucion = 'EJECUTANDO'
        AND ejecutado_at IS NULL)
      OR
      (estado_ejecucion = 'EJECUTADO'
        AND ejecutado_at IS NOT NULL
        AND error_netbox IS NULL)
      OR
      (estado_ejecucion = 'ERROR'
        AND ejecutado_at IS NOT NULL
        AND NULLIF(BTRIM(error_netbox), '') IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS movimiento_detalle_movimiento_idx
  ON public.movimiento_detalle(movimiento_id);
CREATE INDEX IF NOT EXISTS movimiento_detalle_estado_idx
  ON public.movimiento_detalle(estado_ejecucion);
CREATE INDEX IF NOT EXISTS movimiento_detalle_equipo_anterior_idx
  ON public.movimiento_detalle(equipo_anterior_netbox_id)
  WHERE equipo_anterior_netbox_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS movimiento_detalle_nombre_propuesto_idx
  ON public.movimiento_detalle(nombre_propuesto)
  WHERE nombre_propuesto IS NOT NULL;

-- ============================================================
-- 3. UPDATED_AT
-- Reutiliza public.actualizar_updated_at() de la etapa 1.
-- ============================================================

DROP TRIGGER IF EXISTS movimientos_actualizar_updated_at
  ON public.movimientos;
CREATE TRIGGER movimientos_actualizar_updated_at
BEFORE UPDATE ON public.movimientos
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_updated_at();

DROP TRIGGER IF EXISTS movimiento_detalle_actualizar_updated_at
  ON public.movimiento_detalle;
CREATE TRIGGER movimiento_detalle_actualizar_updated_at
BEFORE UPDATE ON public.movimiento_detalle
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_updated_at();

-- ============================================================
-- 4. BLOQUEO ATOMICO CONTRA DOBLE APROBACION
-- La futura Edge Function llamara esta funcion antes de tocar
-- NetBox. Solo un administrador podra pasar a PROCESANDO.
-- ============================================================

CREATE OR REPLACE FUNCTION public.iniciar_procesamiento_movimiento(
  p_movimiento_id BIGINT
)
RETURNS public.movimientos
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_movimiento public.movimientos;
BEGIN
  IF NOT public.es_admin() THEN
    RAISE EXCEPTION 'No autorizado';
  END IF;

  UPDATE public.movimientos
  SET
    estado = 'PROCESANDO',
    error_general = NULL
  WHERE id = p_movimiento_id
    AND estado IN ('PENDIENTE', 'EN_REVISION', 'ERROR')
  RETURNING * INTO v_movimiento;

  IF NOT FOUND THEN
    RAISE EXCEPTION
      'El movimiento no existe o ya esta siendo procesado/finalizado';
  END IF;

  RETURN v_movimiento;
END;
$$;

REVOKE ALL ON FUNCTION public.iniciar_procesamiento_movimiento(BIGINT)
  FROM PUBLIC;
GRANT EXECUTE
  ON FUNCTION public.iniciar_procesamiento_movimiento(BIGINT)
  TO authenticated;

-- ============================================================
-- 5. ROW LEVEL SECURITY
-- Los tecnicos usaran funciones controladas que se agregaran
-- despues. No se permite acceso anonimo directo a estas tablas.
-- ============================================================

ALTER TABLE public.movimientos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimiento_detalle ENABLE ROW LEVEL SECURITY;

CREATE POLICY movimientos_gestion_admin
ON public.movimientos FOR ALL TO authenticated
USING (public.es_admin())
WITH CHECK (public.es_admin());

CREATE POLICY movimiento_detalle_gestion_admin
ON public.movimiento_detalle FOR ALL TO authenticated
USING (public.es_admin())
WITH CHECK (public.es_admin());

GRANT SELECT, INSERT, UPDATE, DELETE ON
  public.movimientos,
  public.movimiento_detalle
TO authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

COMMIT;

-- ============================================================
-- VERIFICACION MANUAL DESPUES DE EJECUTAR
-- ============================================================
-- SELECT table_name
-- FROM information_schema.tables
-- WHERE table_schema = 'public'
--   AND table_name IN ('movimientos', 'movimiento_detalle')
-- ORDER BY table_name;
--
-- SELECT conrelid::regclass AS tabla, conname,
--        pg_get_constraintdef(oid) AS definicion
-- FROM pg_constraint
-- WHERE conrelid IN (
--   'public.movimientos'::regclass,
--   'public.movimiento_detalle'::regclass
-- )
-- ORDER BY conrelid::regclass::text, conname;

