-- ============================================================
-- PROYECTO ACCESOS V2 - ETAPA 3
-- Inventario, solicitud, entrega y devolucion de llaves.
--
-- Requiere haber ejecutado 01_base_v2.sql y
-- 02_movimientos_equipos_v2.sql.
-- No elimina tablas ni datos.
-- ============================================================

BEGIN;

-- ============================================================
-- 1. INVENTARIO DE LLAVES POR NODO
-- ============================================================

CREATE TABLE IF NOT EXISTS public.llaves_nodo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nodo_id INTEGER NOT NULL
    REFERENCES public.nodos(id) ON DELETE RESTRICT,
  codigo TEXT NOT NULL,
  estado TEXT NOT NULL DEFAULT 'DISPONIBLE',
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT llaves_nodo_codigo_unique UNIQUE (nodo_id, codigo),
  CONSTRAINT llaves_nodo_estado_check
    CHECK (estado IN ('DISPONIBLE', 'PRESTADA', 'INACTIVA')),
  CONSTRAINT llaves_nodo_inactiva_check
    CHECK (activo = TRUE OR estado = 'INACTIVA')
);

CREATE INDEX IF NOT EXISTS llaves_nodo_nodo_idx
  ON public.llaves_nodo(nodo_id);
CREATE INDEX IF NOT EXISTS llaves_nodo_estado_idx
  ON public.llaves_nodo(estado);

-- ============================================================
-- 2. CICLO COMPLETO DEL PRESTAMO
-- Un acceso solo puede registrar una solicitud de llave.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.prestamos_llave (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  acceso_id BIGINT NOT NULL UNIQUE
    REFERENCES public.accesos(id) ON DELETE CASCADE,
  llave_id BIGINT NOT NULL
    REFERENCES public.llaves_nodo(id) ON DELETE RESTRICT,

  nombre_persona TEXT NOT NULL,
  area_id INTEGER NOT NULL
    REFERENCES public.areas(id) ON DELETE RESTRICT,
  estado TEXT NOT NULL DEFAULT 'SOLICITADO',
  observacion TEXT,

  entregado_por UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  entregado_at TIMESTAMPTZ,
  devuelto_por UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  devuelto_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT prestamos_llave_nombre_check
    CHECK (NULLIF(BTRIM(nombre_persona), '') IS NOT NULL),
  CONSTRAINT prestamos_llave_estado_check
    CHECK (estado IN ('SOLICITADO', 'ENTREGADO', 'DEVUELTO', 'CANCELADO')),
  CONSTRAINT prestamos_llave_fechas_check
    CHECK (
      devuelto_at IS NULL
      OR entregado_at IS NOT NULL AND devuelto_at >= entregado_at
    ),
  CONSTRAINT prestamos_llave_estado_consistente_check
    CHECK (
      (estado = 'SOLICITADO'
        AND entregado_por IS NULL
        AND entregado_at IS NULL
        AND devuelto_por IS NULL
        AND devuelto_at IS NULL)
      OR
      (estado = 'ENTREGADO'
        AND entregado_por IS NOT NULL
        AND entregado_at IS NOT NULL
        AND devuelto_por IS NULL
        AND devuelto_at IS NULL)
      OR
      (estado = 'DEVUELTO'
        AND entregado_por IS NOT NULL
        AND entregado_at IS NOT NULL
        AND devuelto_por IS NOT NULL
        AND devuelto_at IS NOT NULL)
      OR
      (estado = 'CANCELADO'
        AND entregado_por IS NULL
        AND entregado_at IS NULL
        AND devuelto_por IS NULL
        AND devuelto_at IS NULL)
    )
);

-- Una llave no puede estar asociada a dos prestamos activos.
CREATE UNIQUE INDEX IF NOT EXISTS prestamos_llave_activo_unique
  ON public.prestamos_llave(llave_id)
  WHERE estado IN ('SOLICITADO', 'ENTREGADO');

CREATE INDEX IF NOT EXISTS prestamos_llave_estado_idx
  ON public.prestamos_llave(estado);
CREATE INDEX IF NOT EXISTS prestamos_llave_created_at_idx
  ON public.prestamos_llave(created_at DESC);

-- ============================================================
-- 3. UPDATED_AT
-- ============================================================

DROP TRIGGER IF EXISTS llaves_nodo_actualizar_updated_at
  ON public.llaves_nodo;
CREATE TRIGGER llaves_nodo_actualizar_updated_at
BEFORE UPDATE ON public.llaves_nodo
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_updated_at();

DROP TRIGGER IF EXISTS prestamos_llave_actualizar_updated_at
  ON public.prestamos_llave;
CREATE TRIGGER prestamos_llave_actualizar_updated_at
BEFORE UPDATE ON public.prestamos_llave
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_updated_at();

-- ============================================================
-- 4. ENTREGA ATOMICA DE LLAVE
-- Bloquea el prestamo y la llave durante la operacion para
-- impedir entregas simultaneas.
-- ============================================================

CREATE OR REPLACE FUNCTION public.entregar_llave(
  p_prestamo_id BIGINT
)
RETURNS public.prestamos_llave
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_prestamo public.prestamos_llave;
  v_llave public.llaves_nodo;
  v_nodo_acceso INTEGER;
BEGIN
  IF NOT public.es_admin() THEN
    RAISE EXCEPTION 'No autorizado';
  END IF;

  SELECT * INTO v_prestamo
  FROM public.prestamos_llave
  WHERE id = p_prestamo_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'El prestamo no existe';
  END IF;

  IF v_prestamo.estado <> 'SOLICITADO' THEN
    RAISE EXCEPTION 'La solicitud ya fue procesada';
  END IF;

  SELECT * INTO v_llave
  FROM public.llaves_nodo
  WHERE id = v_prestamo.llave_id
  FOR UPDATE;

  IF NOT FOUND OR v_llave.activo = FALSE OR v_llave.estado <> 'DISPONIBLE' THEN
    RAISE EXCEPTION 'La llave no esta disponible';
  END IF;

  SELECT nodo_id INTO v_nodo_acceso
  FROM public.accesos
  WHERE id = v_prestamo.acceso_id;

  IF v_nodo_acceso IS NULL OR v_nodo_acceso <> v_llave.nodo_id THEN
    RAISE EXCEPTION 'La llave no pertenece al nodo del acceso';
  END IF;

  UPDATE public.llaves_nodo
  SET estado = 'PRESTADA'
  WHERE id = v_llave.id;

  UPDATE public.prestamos_llave
  SET
    estado = 'ENTREGADO',
    entregado_por = auth.uid(),
    entregado_at = NOW()
  WHERE id = v_prestamo.id
  RETURNING * INTO v_prestamo;

  RETURN v_prestamo;
END;
$$;

REVOKE ALL ON FUNCTION public.entregar_llave(BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.entregar_llave(BIGINT) TO authenticated;

-- ============================================================
-- 5. DEVOLUCION ATOMICA DE LLAVE
-- ============================================================

CREATE OR REPLACE FUNCTION public.devolver_llave(
  p_prestamo_id BIGINT
)
RETURNS public.prestamos_llave
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_prestamo public.prestamos_llave;
  v_llave public.llaves_nodo;
BEGIN
  IF NOT public.es_admin() THEN
    RAISE EXCEPTION 'No autorizado';
  END IF;

  SELECT * INTO v_prestamo
  FROM public.prestamos_llave
  WHERE id = p_prestamo_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'El prestamo no existe';
  END IF;

  IF v_prestamo.estado <> 'ENTREGADO' THEN
    RAISE EXCEPTION 'La llave no figura como entregada';
  END IF;

  SELECT * INTO v_llave
  FROM public.llaves_nodo
  WHERE id = v_prestamo.llave_id
  FOR UPDATE;

  IF NOT FOUND OR v_llave.estado <> 'PRESTADA' THEN
    RAISE EXCEPTION 'El estado de la llave es inconsistente';
  END IF;

  UPDATE public.llaves_nodo
  SET estado = 'DISPONIBLE'
  WHERE id = v_llave.id;

  UPDATE public.prestamos_llave
  SET
    estado = 'DEVUELTO',
    devuelto_por = auth.uid(),
    devuelto_at = NOW()
  WHERE id = v_prestamo.id
  RETURNING * INTO v_prestamo;

  RETURN v_prestamo;
END;
$$;

REVOKE ALL ON FUNCTION public.devolver_llave(BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.devolver_llave(BIGINT) TO authenticated;

-- ============================================================
-- 6. ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.llaves_nodo ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prestamos_llave ENABLE ROW LEVEL SECURITY;

CREATE POLICY llaves_nodo_gestion_admin
ON public.llaves_nodo FOR ALL TO authenticated
USING (public.es_admin())
WITH CHECK (public.es_admin());

CREATE POLICY prestamos_llave_gestion_admin
ON public.prestamos_llave FOR ALL TO authenticated
USING (public.es_admin())
WITH CHECK (public.es_admin());

GRANT SELECT, INSERT, UPDATE, DELETE ON
  public.llaves_nodo,
  public.prestamos_llave
TO authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

COMMIT;

-- ============================================================
-- VERIFICACION MANUAL DESPUES DE EJECUTAR
-- ============================================================
-- SELECT table_name
-- FROM information_schema.tables
-- WHERE table_schema = 'public'
--   AND table_name IN ('llaves_nodo', 'prestamos_llave')
-- ORDER BY table_name;
